export const SET_ACTIVE_LOANS = "SET_ACTIVE_LOANS";
export const ADD_ACTIVE_LOAN = "ADD_ACTIVE_LOAN";
export const MOD_ACTIVE_LOAN = "MOD_ACTIVE_LOAN";
export const SET_SCHEDULE = "SET_SCHEDULE";
export const SET_STICKYNESS = "SET_STICKYNESS";
